---
# This workflow is meant to be hosted in two repositories:
# - The dispatcher
# - The renderer
#
# The dispatcher runs the dispatch job on a pull_request event, and triggers
# the renderer to run the render job, using information from the pull request.
#
# This level of separation is necessary:
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests
name: Render Pull Request
on:
  # For a description, see:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
  pull_request_target:
    paths-ignore:
      - README.md
    branches:
      - main

  workflow_dispatch:
    inputs:
      pull_request_id:
        description: |
          The number assigned to the pull request. See:
          https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally#modifying-an-inactive-pull-request-locally
        required: true

jobs:
  dispatch:
    name: Dispatch to other repository
    runs-on: ubuntu-latest
    if: "${{ github.event_name == 'pull_request' }}"
    steps:
      - name: Run script to trigger GitHub Action workflow in other repository
        shell: bash
        env:
          # Pull Request payload example:
          # https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#pull_request
          PULL_REQUEST_ID: "${{ github.event.pull_request.number }}"
          PERSONAL_ACCESS_TOKEN: "${{ secrets.PULL_REQUEST_TOKEN }}"
        run: |
          set -eu
          curl --fail \
               --silent \
               --show-error \
               --location \
               'https://raw.githubusercontent.com/mawillcockson/pr.texasbutterfliesmonitoring.org/main/workflow_command.sh' \
               | bash

      - name: Make Comment
        shell: bash
        env:
          GITHUB_TOKEN: "${{ github.token }}"
        run: |
          set -eu
          printf \
          'The changes in this pull request have been submitted to be included in a demo version of the site.
                    
          [If [`hugo`](https://gohugo.io/) can build this pull request, then that build can be viewed here](%s)
          
          If `hugo` encountered an error, [there may be some logs accessible here](https://github.com/mawillcockson/pr.texasbutterfliesmonitoring.org/actions/workflows/pull_request.yaml?query=event%3Aworkflow_dispatch+branch%3Amain).
          
          _note: this comment was generated automatically_' \
              "${RENDER_URL}" \
              | jq '{"body":.}' --raw-input --slurp --compact-output \
              | curl \
                  --request POST \
                  --header "Accept: application/vnd.github.v3+json" \
                  --user "mawillcockson:${GITHUB_TOKEN}"
                  "https://api.github.com/repos/mawillcockson/TXButterflies.github.io/issues/${PULL_REQUEST_ID}/comments" \
                  --data "@-"

  render:
    name: Build pull request site with Hugo
    runs-on: ubuntu-latest
    if: "${{ github.event_name == 'workflow_dispatch' }}"
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages/

      - name: Render pull request
        shell: bash
        env:
          PULL_REQUEST_ID: "${{ github.event.inputs.pull_request_id }}"
        run: |
          set -eu
          ACTIONS_USERNAME='github-actions'
          ACTIONS_EMAIL='41898282+github-actions[bot]@users.noreply.github.com'
          RENDER_URL="https://mawillcockson.github.io/pr.texasbutterfliesmonitoring.org/${PULL_REQUEST_ID}/"
          git config --global user.name "${ACTIONS_USERNAME}"
          git config --global user.email "${ACTIONS_EMAIL}"
          git init "${GITHUB_WORKSPACE}/pull_request/"
          cd "${GITHUB_WORKSPACE}/pull_request/"
          git remote add origin 'https://github.com/TXButterflies/TXButterflies.github.io.git'
          git fetch origin "refs/pull/${PULL_REQUEST_ID}/head"
          git checkout FETCH_HEAD
          cd "${GITHUB_WORKSPACE}"
          sudo apt install -y snap jq
          sudo snap install hugo --channel=extended
          mkdir -p "${GITHUB_WORKSPACE}/gh-pages/${PULL_REQUEST_ID}/"
          /snap/bin/hugo \
              --baseURL "${RENDER_URL}" \
              --source "${GITHUB_WORKSPACE}/pull_request/" \
              --destination "${GITHUB_WORKSPACE}/gh-pages/${PULL_REQUEST_ID}" \
              --verbose
          cd "${GITHUB_WORKSPACE}/gh-pages/"
          git add -A :/
          git commit -m "publish TXButterflies/TXButterflies.github.io#${PULL_REQUEST_ID}"
          git push
...
