---
# This workflow is meant to be hosted in two repositories:
# - The dispatcher
# - The renderer
#
# The dispatcher runs the dispatch job on a pull_request event, and triggers
# the renderer to run the render job, using information from the pull request.
#
# This level of separation is necessary:
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests
name: Render Pull Request
on:
  # For a description, see:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
  pull_request_target:
    paths-ignore:
      - README.md
    branches:
      - main

  workflow_dispatch:
    inputs:
      pull_request_id:
        description: |
          The number assigned to the pull request. See:
          https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally#modifying-an-inactive-pull-request-locally
        required: true

jobs:
  dispatch:
    name: Dispatch to other repository
    runs-on: ubuntu-latest
    if: "${{ github.event_name == 'pull_request_target' }}"
    steps:
      - name: Run script to trigger GitHub Action workflow in other repository
        shell: bash
        env:
          # Pull Request payload example:
          # https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#pull_request
          PULL_REQUEST_ID: "${{ github.event.pull_request.number }}"
          # PERSONAL_ACCESS_TOKEN is a token generated for the account hosting
          # the rendering repository, not the account running this script.
          # Generate one here:
          # https://github.com/settings/tokens/new
          # The token should have public_repo scope set, and the user the token
          # was generated for should have the ability to trigger
          # workflow_dispatch events in the rendering repository.
          PULL_REQUEST_USER: "${{ secrets.PULL_REQUEST_USER }}"
          PULL_REQUEST_TOKEN: "${{ secrets.PULL_REQUEST_TOKEN }}"
          RENDER_REPOSITORY_OWNER: "${{ github.repository_owner }}"
          RENDER_REPOSITORY_NAME: "pr.texasbutterfliesmonitoring.org"
        run: |
          set -eu
          jq --null-input --compact-output '{
              "ref": $github_ref,
              "inputs": {
                  "pull_request_id": $pull_request_id,
              }
          }' \
              --arg github_ref "${GITHUB_REF}" \
              --arg pull_request_id "${PULL_REQUEST_ID}" \
          | curl \
              --request POST \
              --header "Accept: application/vnd.github.v3+json" \
              --user "${PULL_REQUEST_USER}:${PULL_REQUEST_TOKEN}" \
              --post301 --post302 --post303 \
              --data "@-" \
              --url "https://api.github.com/repos/${RENDER_REPOSITORY_OWNER}/${RENDER_REPOSITORY_NAME}/actions/workflows/pull_request.yaml/dispatches"

      - name: Make Comment
        shell: bash
        env:
          COMMENT_USER: "github-actions"
          GITHUB_TOKEN: "${{ github.token }}"
          # See: https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#webhook-payload-example-30
          PULL_REQUEST_COMMENTS_URL: "${{ github.event.pull_request.issue_url }}"
          RENDER_HOMEPAGE: "https://pr.texasbutterfliesmonitoring.org/${{ github.event.pull_request.number }}/index.html"
          RENDER_REPOSITORY_OWNER: "${{ github.repository_owner }}"
          RENDER_REPOSITORY_NAME: "pr.texasbutterfliesmonitoring.org"
          # This filename
          WORKFLOW_FILE: "pull_request.yaml"
        run: |
          set -eu
          printf \
          '# DO NOT MERGE BEFORE PREVIEWING THE CHANGES

          [Preview the changes at this link.](%s)

          If you have visited the above link before, you may have to refresh your browser to see the changes. This is due to browsers caching data from websites. [This link has more information about this](https://refreshyourcache.com/en/cache/).

          If the preview looks fine, you can merge the pull request.

          If the preview is not fine, or not available, [there are logs available at this link.](<https://github.com/%s/%s/actions/workflows/%s?query=event%3Aworkflow_dispatch+branch%3Amain>)
          
          _note: this comment was generated automatically_' \
              "${RENDER_HOMEPAGE}" \
              "${RENDER_REPOSITORY_OWNER}" \
              "${RENDER_REPOSITORY_NAME}" \
              "${WORKFLOW_FILE}" \
              | jq '{"body":.}' --raw-input --slurp --compact-output \
              | curl \
                  --request POST \
                  --header "Accept: application/vnd.github.v3+json" \
                  --user "${COMMENT_USER}:${GITHUB_TOKEN}" \
                  --data "@-" \
                  --url "${PULL_REQUEST_COMMENTS_URL}/comments"

  render:
    name: Build pull request site with Hugo
    runs-on: ubuntu-latest
    if: "${{ github.event_name == 'workflow_dispatch' }}"
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages/

      - name: Install hugo
        shell: bash
        env:
          GITHUB_WORKSPACE: "${{ github.workspace }}"
        run: |
          # See: https://docs.github.com/en/rest/reference/repos#releases
          set -eu
          HUGO_DIR="${GITHUB_WORKSPACE}/hugo"
          mkdir -p "${HUGO_DIR}"
          eval "$(curl --fail \
              --silent \
              --show-error \
              --location \
              --url 'https://api.github.com/repos/gohugoio/hugo/releases/latest' \
              | jq --compact-output --raw-output '.assets |
                  (
                    map(select(.name | test("^hugo_extended_\\d+\\.\\d+\\.\\d+_Linux-64bit.tar.gz$")))[0]
                    | ["HUGO_FILENAME='"'"'" + .name + "'"'"'", "HUGO_URL='"'"'" + .browser_download_url + "'"'"'"]
                  )
                  +
                  (
                    map(select(.name | test("^hugo_\\d+\\.\\d+\\.\\d+_checksums.txt$")))[0]
                    | ["CHECKSUM_FILENAME='"'"'" + .name + "'"'"'", "CHECKSUM_URL='"'"'" + .browser_download_url + "'"'"'"]
                  )
                  | .[]')"
          curl --fail \
               --location \
               --url "${CHECKSUM_URL}" \
               --output "${HUGO_DIR}/${CHECKSUM_FILENAME}" &
          CHECKSUM_PID=$!
          curl --fail \
               --location \
               --url "${HUGO_URL}" \
               --output "${HUGO_DIR}/${HUGO_FILENAME}" &
          HUGO_PID=$!
          wait "${CHECKSUM_PID}" "${HUGO_PID}"
          (cd "${HUGO_DIR}" \
              && grep --no-messages \
                      --no-filename \
                      --fixed-strings \
                      "${HUGO_FILENAME}" \
                      "${CHECKSUM_FILENAME}" \
              | sha256sum --check)
          tar -vxzf "${HUGO_DIR}/${HUGO_FILENAME}" --overwrite -C "${HUGO_DIR}"
          rm "${HUGO_DIR}/LICENSE" "${HUGO_DIR}/README.md" "${HUGO_DIR}/${HUGO_FILENAME}" "${HUGO_DIR}/${CHECKSUM_FILENAME}"
          echo "HUGO_BIN=${HUGO_DIR}/hugo" >> "${GITHUB_ENV}"

      - name: Render pull request
        shell: bash
        env:
          PULL_REQUEST_ID: "${{ github.event.inputs.pull_request_id }}"
          ACTIONS_USERNAME: "github-actions"
          ACTIONS_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
          HUGO_BASEURL: "https://pr.texasbutterfliesmonitoring.org/${{ github.event.inputs.pull_request_id }}/"
          # The repository where the pull request is; the dispatching repository
          REPOSITORY_OF_PULL_REQUEST: "TXButterflies/TXButterflies.github.io"
          SOURCE: "${{ github.workspace }}/pull_request/"
          DESTINATION: "${{ github.workspace }}/gh-pages/${{ github.event.inputs.pull_request_id }}"
        run: |
          set -eu
          git config --global user.name "${ACTIONS_USERNAME}"
          git config --global user.email "${ACTIONS_EMAIL}"
          git init "${GITHUB_WORKSPACE}/pull_request/"
          cd "${GITHUB_WORKSPACE}/pull_request/"
          git remote add origin "https://github.com/${REPOSITORY_OF_PULL_REQUEST}.git"
          git fetch origin "refs/pull/${PULL_REQUEST_ID}/merge"
          git checkout FETCH_HEAD
          cd "${GITHUB_WORKSPACE}"
          mkdir -p "${DESTINATION}"
          "${HUGO_BIN}" env --source "${SOURCE}"
          "${HUGO_BIN}" config --source "${SOURCE}"
          "${HUGO_BIN}" \
              --source "${SOURCE}" \
              --destination "${DESTINATION}" \
              --cleanDestinationDir
          cd "${GITHUB_WORKSPACE}/gh-pages/"
          git add -A :/
          git commit -m "publish ${REPOSITORY_OF_PULL_REQUEST}#${PULL_REQUEST_ID}"
          git push
...
